spring:
  application:
    name: bookinghotelagent

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookinghotel}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:dummy}
    password: ${SMTP_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  openai:
    api-key: ${OPENAI_API_KEY:dummy}
    model: gpt-4.1-mini

logging:
  level:
    dev.langchain4j: DEBUG
    dev.langchain4j.model.openai: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.boot.autoconfigure.h2: DEBUG
    org.springframework.mail: INFO # on rend Ã§a configurable

management:
  endpoints:
    web:
      exposure:
        include: "*"
